website/views.py
from io import BytesIO
from flask import  url_for
import os
from flask import Blueprint, flash, jsonify, redirect, render_template, request, send_file, url_for
from  .models import Admin, Formateur
from . import x
import base64
from datetime import datetime
from collections import defaultdict
from flask import session

def calculate_privilege_percentages(admins):
    try:
        aj_count = 0
        del_count = 0
        modf_count = 0

        total_admins = len(admins)
        total=0

        for admin in admins:
            for privilege in admin.privileges:
                if privilege == 'aj':
                    aj_count += 1
                elif privilege == 'del':
                    del_count += 1
                elif privilege == 'mod':
                    modf_count += 1
                total=total+1


        return [aj_count, del_count, modf_count]

    except Exception as e:
        print("Error calculating privilege percentages:", e)
        return [0, 0, 0]  
views = Blueprint('views', __name__)
@views.context_processor
def override_url_for():
    return dict(url_for=dated_url_for)

def dated_url_for(endpoint, **values):
    if endpoint == 'static':
        filename = values.get('filename', None)
        if filename:
            file_path = os.path.join(views.root_path,
                                 endpoint, filename)
            values['q'] = int(os.stat(file_path).st_mtime)
    return url_for(endpoint, **values)

@views.route('/')
def home():
    if 'admin' not in session:
        session['admin'] = None

    return render_template("index.html")

def get_formateurs_with_domains():
    try:
        conn = x.connect()
        cursor = conn.cursor()

        query = """
        SELECT firstname, lastname, age, birthday, state, country, number, address, id AS formateur_id, email, linkedin, dateAjout
        FROM formateur
        """

        cursor.execute(query)
        results = cursor.fetchall()

        formateurs_dict = {}
        for row in results:
            formateur_id = row[8]
            if formateur_id not in formateurs_dict:
                formateurs_dict[formateur_id] = Formateur(row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10],row[11])
        query = """
        SELECT formateur_id, domain_name
        FROM domain
        """
        cursor.execute(query)
        domain_results = cursor.fetchall()

        for domain_row in domain_results:
            formateur_id = domain_row[0]
            if formateur_id in formateurs_dict:
                formateurs_dict[formateur_id].domains.append(domain_row[1])

        cursor.close()

        formateurs = list(formateurs_dict.values())
        return formateurs

    except Exception as e:
        print("Error while retrieving formateurs:", e)
        return []

@views.route('/dashboard')
def dashboard():
    admins = get_admins()  
    formateurs = get_formateurs_with_domains()
    domains = []
    countries = [formateur.country for formateur in formateurs if formateur.country]
    countries = list(set(country.capitalize() for country in countries))
    for formateur in formateurs:
        for domain in formateur.domains:
            normalized_domain = domain.strip().lower()
            if normalized_domain not in domains:
                domains.append(normalized_domain)
    formateurs_count = len(formateurs)
    formateurs_by_month = count_formateurs_by_month(formateurs)
    

    activities_data = calculate_activities_per_month(admins)
    top_admins = get_top_active_admins(admins, n=3) 
    privi=calculate_privilege_percentages(admins)


    return render_template('dashboard.html',admins=admins,activities_data=activities_data,top_admins=top_admins,privi=privi,number=formateurs_count, formateurs_by_month=formateurs_by_month,domains=domains,countries=countries)

@views.route('/profile')
def profile():
    return render_template('profile.html')

@views.route('/settings')
def settings():
    return render_template('settings.html')

@views.route('/notification')
def notification():
    notifications=get_admin_notifications()
    return render_template('notification.html',notifications=notifications)

@views.route('/formateurs')
def formateurs():
    formateurs = get_formateurs_with_domains()
    return render_template('formateurs.html',formateurs=formateurs)
@views.route('/about.html')
def about():
    return render_template('about.html')

@views.route('/form.html')
def form():
    return render_template('form.html')

def get_image_data_from_database(formateur_id):
    try:
        conn = x.connect()
        cursor = conn.cursor()

        query = "SELECT image FROM formateur WHERE id = %s"
        cursor.execute(query, (formateur_id,))

        image_data = cursor.fetchone()[0]

        return image_data

    except Exception as e:
        print("Error fetching image data:", e)
        return None

@views.route('/get_image/<int:formateur_id>')
def get_image(formateur_id):
    image_data = get_image_data_from_database(formateur_id)
    if image_data:
        return send_file(BytesIO(image_data), mimetype='image/png')
    return "Image not found", 404

@views.route('/formateur/<int:formateur_id>')
def formateur_detail(formateur_id):
    formateur = get_formateur_by_id(formateur_id)
    return render_template('oneTrainer.html', formateur=formateur)

def get_formateur_by_id(formateur_id):
    try:
        conn = x.connect()
        cursor = conn.cursor()

        query = """
        SELECT f.firstname, f.lastname, f.age, f.birthday, f.state, f.country, f.number, f.address, f.id AS formateur_id, f.email, f.linkedin, f.dateajout, d.domain_name
        FROM formateur AS f
        LEFT JOIN domain AS d ON f.id = d.formateur_id
        WHERE f.id = %s
        """


        cursor.execute(query, (formateur_id,))
        results = cursor.fetchall()

        formateur = None
        for row in results:
            if formateur is None:
                formateur = Formateur(row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10],row[11])
            formateur.domains.append(row[12])

        cursor.close()

        return formateur
    except Exception as e:
        print("Error while retrieving formateur by ID:", e)
        return None

@views.route('/modifier_formateur/<int:formateur_id>', methods=['GET', 'POST'])
def modifier_formateur(formateur_id):
    formateur = get_formateur_by_id(formateur_id)
    if not formateur:
        flash('Formateur not found', 'error')
        return redirect(url_for('views.formateurs'))
    return render_template('modifier.html', formateur=formateur)

from datetime import datetime

@views.route('/update_formateur/<int:formateur_id>', methods=['POST'])
def update_formateur(formateur_id):
    try:
        conn = x.connect()
        cursor = conn.cursor()

        firstname = request.form['firstname']
        lastname = request.form['lastname']
        age = request.form['age']
        birthday = request.form['birthday']
        country = request.form['country']
        state = request.form['state']
        address = request.form['address']
        email = request.form['email']
        linkedin = request.form['linkedin']

        image = None
        if 'image' in request.files and request.files['image'].filename != '':
            image_file = request.files['image']
            image = image_file.read()

        if image:
            query = """
            UPDATE formateur
            SET firstname = %s, lastname = %s, age = %s, birthday = %s, country = %s,
                state = %s, address = %s, email = %s, linkedin = %s, image = %s
            WHERE id = %s
            """
            cursor.execute(query, (firstname, lastname, age, birthday, country, state, address, email, linkedin, image, formateur_id))
        else:
            query = """
            UPDATE formateur
            SET firstname = %s, lastname = %s, age = %s, birthday = %s, country = %s,
                state = %s, address = %s, email = %s, linkedin = %s
            WHERE id = %s
            """
            cursor.execute(query, (firstname, lastname, age, birthday, country, state, address, email, linkedin, formateur_id))

        conn.commit()

        # Add action to the action_admin table if the session has admin info and privileges
        if 'admin' in session and isinstance(session['admin'], dict):
            admin_info = session['admin']
            if 'privileges' in admin_info and admin_info['privileges']:
                action_name = 'mod'  # Assuming 'mod' represents modification
                date = datetime.now()
                id_admin = admin_info.get('id')

                # Insert action into action_admin table
                action_query = """
                INSERT INTO action_admin (id_admin, action_name, date, id_formateur)
                VALUES (%s, %s, %s, %s)
                """
                cursor.execute(action_query, (id_admin, action_name, date, formateur_id))
                conn.commit()

        flash('Formateur modifié', 'success')
        return redirect(url_for('views.formateur_detail', formateur_id=formateur_id))
    except Exception as e:
        flash(f'Error updating formateur: {e}', 'error')
        return redirect(url_for('views.modifier_formateur', formateur_id=formateur_id))
    finally:
        cursor.close()
        conn.close()

def get_cv_data_from_database(formateur_id):
    try:
        conn = x.connect()
        cursor = conn.cursor()

        query = "SELECT cv FROM formateur WHERE id = %s"
        cursor.execute(query, (formateur_id,))

        cv_data = cursor.fetchone()[0]

        return cv_data

    except Exception as e:
        print("Error fetching CV data:", e)
        return None

@views.route('/get_cv/<int:formateur_id>')
def get_cv(formateur_id):
    cv_data = get_cv_data_from_database(formateur_id)
    if cv_data:
        return send_file(BytesIO(cv_data), mimetype='application/pdf')

website/templates/formateurs.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BFA</title>

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='imgs/bfa.png') }}"
      type="image/x-icon"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;0,900;1,400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/formateur.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bubble.css') }}"
    />

    <style>
      .btn-add-admin {
        display: inline-block;
        padding: 10px 20px;
        margin-top: 20px;
        background-color: #007bff;
        color: white;
        text-align: center;
        text-decoration: none;
        border-radius: 5px;
      }

      .btn-add-admin:hover {
        background-color: #0056b3;
      }
      .formateur-container {
        margin-top: 80px; /* Adjust this value as needed */
      }
    </style>
  </head>
  <body>
    <div class="chat-bubble">
      <div class="dots">
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
      </div>
    </div>
    <div class="overlay1" id="overlay">
      <div class="modal1">
        <button class="close-btn1" id="closeBtn">&times;</button>
        <h2>Contactez Nous</h2>
        <form id="contactForm">
          <input type="email" placeholder="Email" required />
          <textarea placeholder="Votre Message" rows="5" required></textarea>
          <button type="submit">Envoyez</button>
        </form>
      </div>
    </div>
    <header class="header d-flex">
      <a href="{{ url_for('views.home') }}">
        <img
          src="{{ url_for('static', filename='imgs/bfa.png') }}"
          alt="BFA"
          class="logo"
        />
      </a>
      <button class="btn-mobile-nav icon-open" type="button">
        <i class="fa-solid fa-bars fa-3x icon-mobile-nav"></i>
      </button>

      <nav class="main-nav">
        <ul class="main-nav-list d-flex">
          <li>
            <button class="btn-mobile-nav icon-close" type="button">
              <i class="fa-solid fa-xmark fa-4x icon-mobile-nav"></i>
            </button>
          </li>
          <li>
            <a href="{{ url_for('views.home') }}" class="main-nav-link"
              >Acceuil</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.form') }}" class="main-nav-link"
              >Qui Sommes</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.formateurs') }}" class="main-nav-link"
              >Nos Formateurs</a
            >
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <section class="formateur-container">
        <div class="formateur-list">
          {% for formateur in formateurs %}
          <div
            class="formateur-card"
            data-formateur-id="{{ formateur.formateur_id }}"
            style="cursor: pointer"
          >
            <img
              src="{{ url_for('views.get_image', formateur_id=formateur.formateur_id) }}"
              alt="{{ formateur.firstname }} {{ formateur.lastname }}"
            />
            <div class="formateur-info">
              <h3>{{ formateur.firstname }} {{ formateur.lastname }}</h3>
              <p>{{ formateur.number }}</p>
              <p>{{ formateur.country }}</p>
              <p>Domains: {{ ', '.join(formateur.domains) }}</p>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="admin-actions">
          <a href="{{ url_for('views.ajouterAdmin') }}" class="btn-add-admin">
            Ajouter Admin
          </a>
        </div>
      </section>
    </main>
    <footer class="footer2" id="footer">
      <div class="container">
        <div class="footer-content d-grid">
          <div class="footer-logo">
            <a href="#"
              ><img
                class="footer-img"
                src="{{ url_for('static', filename='imgs/bfa.png') }}"
                alt=""
            /></a>
          </div>
          <div class="footer-text d-flex">
            <p class="copyright">
              <span class="year"></span> &copy;Some rights reserved
            </p>
            <p class="footer-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore
            </p>
          </div>
        </div>
      </div>
    </footer>

    <script src="{{ url_for('static', filename='js/popup.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bubble.js') }}"></script>
    <script src="{{ url_for('static', filename='js/trainer.js') }}"></script>
  </body>
</html>

website/templates/modifier.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BFA - Modifier Formateur</title>

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='imgs/bfa.png') }}"
      type="image/x-icon"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;0,900;1,400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/onetrainer.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/modifier.css') }}"
    />
  </head>
  <body>
    <header class="header d-flex">
      <a href="{{ url_for('views.home') }}">
        <img
          src="{{ url_for('static', filename='imgs/bfa.png') }}"
          alt="BFA"
          class="logo"
        />
      </a>
      <button class="btn-mobile-nav icon-open" type="button">
        <i class="fa-solid fa-bars fa-3x icon-mobile-nav"></i>
      </button>
      <nav class="main-nav">
        <ul class="main-nav-list d-flex">
          <li>
            <button class="btn-mobile-nav icon-close" type="button">
              <i class="fa-solid fa-xmark fa-4x icon-mobile-nav"></i>
            </button>
          </li>
          <li>
            <a href="{{ url_for('views.home') }}" class="main-nav-link"
              >Acceuil</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.form') }}" class="main-nav-link"
              >Se Connecter</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.formateurs') }}" class="main-nav-link"
              >Nos Formateurs</a
            >
          </li>
          <li><a href="#footer" class="main-nav-link">Contact</a></li>
        </ul>
      </nav>
    </header>
    <main>
      <section id="profile">
        <div class="container">
          <form
            id="modifier-form"
            action="{{ url_for('views.update_formateur', formateur_id=formateur.formateur_id) }}"
            method="POST"
            enctype="multipart/form-data"
          >
            <div class="image-upload">
              <label for="image-input">
                <img
                  src="{{ url_for('views.get_image', formateur_id=formateur.formateur_id) }}"
                  alt="Formateur Image"
                  class="round-image"
                />
                <div class="change-image">Changer l'image</div>
              </label>
              <input
                id="image-input"
                type="file"
                name="image"
                accept="image/*"
                style="display: none"
              />
            </div>
            <div class="form-group">
              <label for="firstname">Prénom</label>
              <input
                type="text"
                id="firstname"
                name="firstname"
                value="{{ formateur.firstname }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="lastname">Nom</label>
              <input
                type="text"
                id="lastname"
                name="lastname"
                value="{{ formateur.lastname }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="age">Age</label>
              <input
                type="number"
                id="age"
                name="age"
                value="{{ formateur.age }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="birthday">Date de Naissance</label>
              <input
                type="date"
                id="birthday"
                name="birthday"
                value="{{ formateur.birthday }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="country">Pays</label>
              <input
                type="text"
                id="country"
                name="country"
                value="{{ formateur.country }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="state">État</label>
              <input
                type="text"
                id="state"
                name="state"
                value="{{ formateur.state }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="address">Adresse</label>
              <input
                type="text"
                id="address"
                name="address"
                value="{{ formateur.address }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input
                type="email"
                id="email"
                name="email"
                value="{{ formateur.email }}"
                required
              />
            </div>
            <div class="form-group">
              <label for="linkedin">LinkedIn</label>
              <input
                type="url"
                id="linkedin"
                name="linkedin"
                value="{{ formateur.linkedin }}"
                required
              />
            </div>
            <button type="submit">Enregistrer</button>
          </form>
        </div>
      </section>
    </main>
    <footer id="footer">
      <a href="#top" class="scroll-to-top"><i class="fas fa-arrow-up"></i></a>
    </footer>
    <script src="{{ url_for('static', filename='js/trainerScroll.js') }}"></script>
  </body>
</html>

website/templates/notification.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Notifications</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/notification.css') }}"
    />
  </head>
  <body>
    <div class="wrapper">
      <h2 class="titre">Notifications des Administrateurs</h2>
      <div class="notifications-container">
        {% if notifications %} {% for notification in notifications %}
        <div class="notification-card">
          <div class="notification-header">
            <span class="admin-name">
              {{ notification.admin_name }} {{ notification.admin_last_name }}
            </span>
            <span class="notification-date">
              {{ notification.date.strftime('%Y-%m-%d %H:%M:%S') }}
            </span>
          </div>
          <div class="notification-body">
            <div class="notification-text">
              {% if notification.action_name == 'aj' %}
              <p class="notification-action">
                {{ notification.admin_name }} {{ notification.admin_last_name }}
                a ajouté le formateur.
              </p>
              {% elif notification.action_name == 'mod' %}
              <p class="notification-action">
                {{ notification.admin_name }} {{ notification.admin_last_name }}
                a modifié le formateur.
              </p>
              {% elif notification.action_name == 'del' %}
              <p class="notification-action">
                {{ notification.admin_name }} {{ notification.admin_last_name }}
                a supprimé le formateur avec ID {{ notification.formateur_id }}.
              </p>
              {% endif %}
            </div>
            {% if notification.action_name != 'del' %}
            <div class="formateur-image-container">
              <img
                src="{{ url_for('views.get_image', formateur_id=notification.formateur_id) }}"
                alt="Image du Formateur"
                class="small-formateur-image"
              />
            </div>
            {% endif %}
          </div>
        </div>
        {% endfor %} {% else %}
        <p>Aucune notification disponible.</p>
        {% endif %}
      </div>
    </div>
  </body>
</html>

website/templates/oneTrainer.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BFA</title>

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='imgs/bfa.png') }}"
      type="image/x-icon"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;0,900;1,400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/onetrainer.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body>
    <div id="delete-modal1" class="modal1">
      <div class="modal1-content">
        <div class="modal1-header">
          <h2>Confirmation</h2>
          <span class="close" id="cancel-delete">&times;</span>
        </div>
        <div class="modal1-body">
          <p>Êtes-vous sûr de vouloir supprimer ce formateur ?</p>
        </div>
        <div class="modal1-footer">
          <button id="confirm-delete">Yes</button>
        </div>
      </div>
    </div>

    <header class="header d-flex">
      <a href="{{ url_for('views.home') }}">
        <img
          src="{{ url_for('static', filename='imgs/bfa.png') }}"
          alt="BFA"
          class="logo"
        />
      </a>
      <button class="btn-mobile-nav icon-open" type="button">
        <i class="fa-solid fa-bars fa-3x icon-mobile-nav"></i>
      </button>
      <nav class="main-nav">
        <ul class="main-nav-list d-flex">
          <li>
            <button class="btn-mobile-nav icon-close" type="button">
              <i class="fa-solid fa-xmark fa-4x icon-mobile-nav"></i>
            </button>
          </li>
          <li>
            <a href="{{ url_for('views.home') }}" class="main-nav-link"
              >Acceuil</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.form') }}" class="main-nav-link"
              >Se Connecter</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.formateurs') }}" class="main-nav-link"
              >Nos Formateurs</a
            >
          </li>
          <li>
            <a href="{{ url_for('views.logout') }}" class="main-nav-link"
              >Déconnecter</a
            >
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <section id="profile">
        <div class="container">
          <img
            src="{{ url_for('views.get_image', formateur_id=formateur.formateur_id) }}"
            alt="Formateur Image"
          />
          <div class="contact">
            <a href="mailto:{{ formateur.email }}"
              ><i class="fas fa-envelope"></i
            ></a>
            <a href="{{ formateur.linkedin }}" target="_blank"
              ><i class="fab fa-linkedin"></i
            ></a>
            <a
              href="{{ url_for('views.get_cv', formateur_id=formateur.formateur_id) }}"
              target="_blank"
            >
              <button>Télécharger CV</button>
            </a>
          </div>
        </div>
        <div
          class="right-column"
          data-formateur-id="{{ formateur.formateur_id }}"
        >
          <h2 class="heading-secondary">
            {{ formateur.firstname }} {{ formateur.lastname }}
          </h2>
          <p>Age: {{ formateur.age }}</p>
          <p>Birth Date: {{ formateur.birthday }}</p>
          <p>Country: {{ formateur.country }}</p>
          <p>State: {{ formateur.state }}</p>
          <p>Address: {{ formateur.address }}</p>
          {% if session.get('admin') %} {% if session['admin'] is string %}
          <!-- If the session only contains an email, the user is a super_admin -->
          <button id="modifier-button">Modifier</button>
          <button id="supprimer-button">Supprimer</button>
          {% elif session['admin'].get('privileges') %}
          <!-- If the session contains privileges, the user is an admin -->
          {% if 'mod' in session['admin']['privileges'] %}
          <button id="modifier-button">Modifier</button>
          {% endif %} {% if 'del' in session['admin']['privileges'] %}
          <button id="supprimer-button">Supprimer</button>
          {% endif %} {% else %}
          <!-- If the session does not contain privileges, treat as internaute -->
          <!-- No buttons displayed for internaute -->
          {% endif %} {% else %}
          <!-- If no session['admin'], assume the user is an internaute -->
          <!-- No buttons displayed for internaute -->
          {% endif %}
        </div>
        <div class="cv-container">
          <iframe
            id="cv-iframe"
            src="{{ url_for('views.get_cv', formateur_id=formateur.formateur_id) }}"
          ></iframe>
        </div>
      </section>
      <section class="section-services">
        <div class="container-exp">
          <h2 class="heading-secondary">Expertise</h2>
          <p>Domains: {{ ', '.join(formateur.domains) }}</p>
          <div class="partition"></div>
          <div class="services d-grid"></div>
        </div>
      </section>
    </main>
    <footer id="footer">
      <a href="#top" class="scroll-to-top"><i class="fas fa-arrow-up"></i></a>
    </footer>
    <script src="{{ url_for('static', filename='js/trainerScroll.js') }}"></script>
    <script src="{{ url_for('static', filename='js/trainer.js') }}"></script>
  </body>
</html>